import type { Metadata } from "next";

import { Poppins } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Provider from "./Provider";
import Image from "next/image";
import { Suspense } from "react";
import Loading from "./loading";
import { redirect } from "next/navigation";
import Header from "./components/Header/Header";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div>
          <Provider>
            {/* <AppBar /> */}
            <AntdRegistry>
              <div className="max-w-[393px] mx-auto relative">
                <Header />

                <main className="bg-white h-[calc(100dvh)] relative">
                  <Suspense fallback={<Loading />}>{children}</Suspense>
                </main>
              </div>
            </AntdRegistry>
          </Provider>
        </div>
      </body>
    </html>
  );
}
